config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'theApp'  => 'static_pages#theApp'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def theApp
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
		<h1> About </h1>
			<p> This app is a prototype built by John Mullin for ORM Technologies. It's purpose serves to deonstrate John's:</p>
				<ul>
  					<li type="square">Capabilities in learning a new language and new concepts</li>
 					<li type="square">Pre-established foundation in Ruby</li>
  					<li type="square">Comfrotability with the rails framework</li>
				</ul>
		<h3> Strengths Developed</h3>
				<ul>
  				<li type="square">Static Pages</li>
 				<li type="square">Ruby Language</li>
  				<li type="square">App layout</li>
  				<li type="square">MVC Architecture</li>
 		 		<li type="square">Modeling Users</li>
  				<li type="square">Sign-up Verification</li>
 		 		<li type="square">Managing applicatin resources</li>
  				<li type="square">Rails Framework</li>
 		 		<li type="square">Git control</li>
  				<li type="square">Development to Deployment</li>
 		 		<li type="square">and much more</li>
			</ul>

			<h3> Contact </h3>

				<li><a href="mailto:jmullin@smu.edu?Subject=I%saw%20your%20app!" target="_top">jmullin@su.edu</a></li>
				<li><p>602.999.0056</p></li>
				<li><p> 6638 Airline Rd. Dallas, TX 75205</p></li>

		

	</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<!doctype html>
<html>
	<body>
		<h1>John Mullin</h1>
		<center>
		<%= link_to image_tag("me2.jpg", alt: "John Mullin"),
              'https://www.linkedin.com/in/john-mullin-9685899b?authType=NAME_SEARCH&authToken=yOQg&locale=en_US&srchid=3567590721456906063998&srchindex=1&srchtotal=161&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A3567590721456906063998%2CVSRPtargetId%3A356759072%2CVSRPcmpt%3Aprimary%2CVSRPnm%3Atrue%2CauthType%3ANAME_SEARCH/' %>
		<p>  </p>
		<a href="mailto:jmullin@smu.edu?Subject=I%saw%20your%20app!" target="_top">jmullin@su.edu</a>
		<p> 602.999.0056</p>
		<p> 6638 Airline Rd. Dallas, TX 75205</p>
	</center>
	</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
	Simply follow your team members that you want to listen to and have your team members follow you back. Once you have your group connections made you can seemlessly share microposts about anything and everything. You can even upload images in your microposts. Enjoy!
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>

      <section class="stats">
        <%= render 'shared/stats' %>
      </section>

      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>

    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Networking App</h1>

    <h2>
      Sign up and start organizaing micropost broadcasts to your team with
      <%= link_to "Teamly", signup_path %>Teamly</a>
      your online communication web app.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Built entirely with Ruby on Rails"),
              signup_path %>
<% end %>

app/views/static_pages/theApp.html.erb
<% provide(:title, 'the App') %>
<!doctype html>
<html>
	<body>
		<h1>The App</h1>
		<p> This is a professional grade web-based Rails application packed with a ton of features. Here is a description of some of the features I choose to include behind the scenes to make this such a clean, fast, secure web app: </p>
		<p><b> Security </b></p>
			<ul>
  				<li type="square">SSL - Secure socket layer encryption for strict transport security</li>
 		 		<li type="square">Bcrypt - Military grade password encryption</li>
			</ul>
		<p><b>  Storage </b></p>
			<ul>
  				<li type="square">SQLite - Back end database </li>
 		 		<li type="square">Amazon S3 - Expansive cloud storage     </li>
			</ul>
		<p><b>  Service </b></p>
			<ul>
  				<li type="square">Puma - Professional web server reliability </li>
 		 		<li type="square">Heroku - Cloud application platform   </li>
			</ul>
		<p><b>  Posting </b></p>
			<ul>
  				<li type="square">MiniMagic - Convenient, seemless picture resizing </li>
 		 		<li type="square">CarrierWave - Picture uploading made easy </li>
			</ul>
	</body>
</html>